### ISSUE TITLE
Failed to activate the git-tabs package

### ISSUE THREAD

**Issue by PointedEars** [anderoonies/git-tabs#21]
**Atom Version**: 1.4.0
**System**: Debian GNU/Linux
**Thrown From**: [git-tabs](https://github.com/anderoonies/git-tabs) package, v0.3.0
### Stack Trace

Failed to activate the git-tabs package

```
At Cannot read property 'path' of null

TypeError: Cannot read property 'path' of null
    at module.exports.getItemPath (/home/pelinux/.atom/packages/git-tabs/lib/utils.coffee:6:29)
    at Object.module.exports.saveTab (/home/pelinux/.atom/packages/git-tabs/lib/git-tabs.coffee:103:26)
    at Object.module.exports.saveTabs (/home/pelinux/.atom/packages/git-tabs/lib/git-tabs.coffee:95:8)
    at Object.module.exports.activate (/home/pelinux/.atom/packages/git-tabs/lib/git-tabs.coffee:50:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:524:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:505:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:500:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:483:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
    at window.onload (file:///usr/share/atom/resources/app.asar/static/index.js:41:9)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
atom-ternjs, vundefined
atomatigit, v1.5.5
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-awk, v0.1.2
autocomplete-bibtex, v0.6.2
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.4.4
autocomplete-xml, v0.8.1
autoupdate-packages, v1.3.1
branch-status, v0.8.1
character-table, v0.4.3
clipboard-plus, v0.5.1
color-picker, v2.0.14
column-select, v0.2.0
compare-files, v0.6.2
css-snippets, v0.9.0
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
emmet, v2.3.18
emmet-snippets-compatibility, v1.0.1
es-navigation, v0.1.5
file-icons, v1.6.14
filesize, v0.4.2
fold-comments, v0.5.0
git-diff-details, v0.21.0
git-go, v1.0.1
git-grep, v0.9.0
git-hide, v0.1.2
git-log, v0.4.1
git-tabs, v0.3.0
highlight-selected, v0.11.1
hyperclick, v0.0.35
hyperclick-php, v0.2.1
javascript-snippets, v1.2.0
js-hyperclick, v1.4.1
js-refactor, v0.6.0
keyboard-localization, v1.4.14
language-apache, v1.4.0
language-diff, v0.4.0
language-gettext, v0.6.1
language-latex, v0.6.1
language-sql-mysql, v0.3.1
latex, v0.28.2
latexer, v0.2.7
line-count-status, v0.0.3
line-jumper, v0.14.1
linter, v1.11.3
linter-checkbashisms, v0.1.5
linter-chktex, v1.2.4
linter-csslint, v1.2.0
linter-htmlhint, v1.0.0
linter-jshint, v1.2.2
linter-less, v2.3.3
linter-mixed-indent, v1.1.0
linter-pylint, v1.2.0
linter-shellcheck, v1.1.0
linter-xmllint, vundefined
local-history, v3.2.3
method-separator, v0.1.4
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
move-status-items, v0.0.11
nav-panel, v0.0.11
navigate, v0.1.13
navigate-indent, v0.1.0
nuclide-find-references, v0.0.35
nuclide-url-hyperclick, v0.0.35
open-recent, v4.0.1
php-debug, v0.2.0
php-extract-method, v0.2.1
php-getters-setters, v0.5.5
pigments, v0.19.7
project-view, v0.4.1
punchclock, v0.6.5
python-isort, v0.0.7
python-tools, v0.6.7
recent-projects, v0.9.5
refactor, v0.6.0
remember-file-positions, v0.2.1
revert-buffer, v0.5.0
svn, v0.0.9
text-manipulation, v0.6.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.2
up2date, v0.1.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, vundefined
xkcd-comics, v0.3.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by anderoonies** [comment]
great—i've seen a similar issue and i'll fix this later tonight

**Comment by Sirfrummel** [comment]
I see it was merged but I guess my atom package hasn't updated yet ?    Thanks by the way... this is by far, my most favorite atom plugin of all time.
